export const countries = [
  {
    iso_3166_1: "AD",
    english_name: "Andorra",
    native_name: "Andorra",
    flag: "🇦🇩",
  },
  {
    iso_3166_1: "AE",
    english_name: "United Arab Emirates",
    native_name: "United Arab Emirates",
    flag: "🇦🇪",
  },
  {
    iso_3166_1: "AF",
    english_name: "Afghanistan",
    native_name: "Afghanistan",
    flag: "🇦🇫",
  },
  {
    iso_3166_1: "AG",
    english_name: "Antigua and Barbuda",
    native_name: "Antigua & Barbuda",
    flag: "🇦🇬",
  },
  {
    iso_3166_1: "AI",
    english_name: "Anguilla",
    native_name: "Anguilla",
    flag: "🇦🇮",
  },
  {
    iso_3166_1: "AL",
    english_name: "Albania",
    native_name: "Albania",
    flag: "🇦🇱",
  },
  {
    iso_3166_1: "AM",
    english_name: "Armenia",
    native_name: "Armenia",
    flag: "🇦🇲",
  },
  {
    iso_3166_1: "AN",
    english_name: "Netherlands Antilles",
    native_name: "Netherlands Antilles",
    flag: "🇦🇳",
  },
  {
    iso_3166_1: "AO",
    english_name: "Angola",
    native_name: "Angola",
    flag: "🇦🇴",
  },
  {
    iso_3166_1: "AQ",
    english_name: "Antarctica",
    native_name: "Antarctica",
    flag: "🇦🇶",
  },
  {
    iso_3166_1: "AR",
    english_name: "Argentina",
    native_name: "Argentina",
    flag: "🇦🇷",
  },
  {
    iso_3166_1: "AS",
    english_name: "American Samoa",
    native_name: "American Samoa",
    flag: "🇦🇸",
  },
  {
    iso_3166_1: "AT",
    english_name: "Austria",
    native_name: "Austria",
    flag: "🇦🇹",
  },
  {
    iso_3166_1: "AU",
    english_name: "Australia",
    native_name: "Australia",
    flag: "🇦🇺",
  },
  {
    iso_3166_1: "AW",
    english_name: "Aruba",
    native_name: "Aruba",
    flag: "🇦🇼",
  },
  {
    iso_3166_1: "AZ",
    english_name: "Azerbaijan",
    native_name: "Azerbaijan",
    flag: "🇦🇿",
  },
  {
    iso_3166_1: "BA",
    english_name: "Bosnia and Herzegovina",
    native_name: "Bosnia & Herzegovina",
    flag: "🇧🇦",
  },
  {
    iso_3166_1: "BB",
    english_name: "Barbados",
    native_name: "Barbados",
    flag: "🇧🇧",
  },
  {
    iso_3166_1: "BD",
    english_name: "Bangladesh",
    native_name: "Bangladesh",
    flag: "🇧🇩",
  },
  {
    iso_3166_1: "BE",
    english_name: "Belgium",
    native_name: "Belgium",
    flag: "🇧🇪",
  },
  {
    iso_3166_1: "BF",
    english_name: "Burkina Faso",
    native_name: "Burkina Faso",
    flag: "🇧🇫",
  },
  {
    iso_3166_1: "BG",
    english_name: "Bulgaria",
    native_name: "Bulgaria",
    flag: "🇧🇬",
  },
  {
    iso_3166_1: "BH",
    english_name: "Bahrain",
    native_name: "Bahrain",
    flag: "🇧🇭",
  },
  {
    iso_3166_1: "BI",
    english_name: "Burundi",
    native_name: "Burundi",
    flag: "🇧🇮",
  },
  {
    iso_3166_1: "BJ",
    english_name: "Benin",
    native_name: "Benin",
    flag: "🇧🇯",
  },
  {
    iso_3166_1: "BM",
    english_name: "Bermuda",
    native_name: "Bermuda",
    flag: "🇧🇲",
  },
  {
    iso_3166_1: "BN",
    english_name: "Brunei Darussalam",
    native_name: "Brunei",
    flag: "🇧🇳",
  },
  {
    iso_3166_1: "BO",
    english_name: "Bolivia",
    native_name: "Bolivia",
    flag: "🇧🇴",
  },
  {
    iso_3166_1: "BR",
    english_name: "Brazil",
    native_name: "Brazil",
    flag: "🇧🇷",
  },
  {
    iso_3166_1: "BS",
    english_name: "Bahamas",
    native_name: "Bahamas",
    flag: "🇧🇸",
  },
  {
    iso_3166_1: "BT",
    english_name: "Bhutan",
    native_name: "Bhutan",
    flag: "🇧🇹",
  },
  {
    iso_3166_1: "BU",
    english_name: "Burma",
    native_name: "Burma",
    flag: "🇲🇲",
  },
  {
    iso_3166_1: "BV",
    english_name: "Bouvet Island",
    native_name: "Bouvet Island",
    flag: "🇧🇻",
  },
  {
    iso_3166_1: "BW",
    english_name: "Botswana",
    native_name: "Botswana",
    flag: "🇧🇼",
  },
  {
    iso_3166_1: "BY",
    english_name: "Belarus",
    native_name: "Belarus",
    flag: "🇧🇾",
  },
  {
    iso_3166_1: "BZ",
    english_name: "Belize",
    native_name: "Belize",
    flag: "🇧🇿",
  },
  {
    iso_3166_1: "CA",
    english_name: "Canada",
    native_name: "Canada",
    flag: "🇨🇦",
  },
  {
    iso_3166_1: "CC",
    english_name: "Cocos  Islands",
    native_name: "Cocos (Keeling) Islands",
    flag: "🇨🇨",
  },
  {
    iso_3166_1: "CD",
    english_name: "Congo",
    native_name: "Democratic Republic of the Congo (Kinshasa)",
    flag: "🇨🇩",
  },
  {
    iso_3166_1: "CF",
    english_name: "Central African Republic",
    native_name: "Central African Republic",
    flag: "🇨🇫",
  },
  {
    iso_3166_1: "CG",
    english_name: "Congo",
    native_name: "Republic of the Congo (Brazzaville)",
    flag: "🇨🇬",
  },
  {
    iso_3166_1: "CH",
    english_name: "Switzerland",
    native_name: "Switzerland",
    flag: "🇨🇭",
  },
  {
    iso_3166_1: "CI",
    english_name: "Cote D'Ivoire",
    native_name: "Côte d'Ivoire",
    flag: "🇨🇮",
  },
  {
    iso_3166_1: "CK",
    english_name: "Cook Islands",
    native_name: "Cook Islands",
    flag: "🇨🇰",
  },
  {
    iso_3166_1: "CL",
    english_name: "Chile",
    native_name: "Chile",
    flag: "🇨🇱",
  },
  {
    iso_3166_1: "CM",
    english_name: "Cameroon",
    native_name: "Cameroon",
    flag: "🇨🇲",
  },
  {
    iso_3166_1: "CN",
    english_name: "China",
    native_name: "China",
    flag: "🇨🇳",
  },
  {
    iso_3166_1: "CO",
    english_name: "Colombia",
    native_name: "Colombia",
    flag: "🇨🇴",
  },
  {
    iso_3166_1: "CR",
    english_name: "Costa Rica",
    native_name: "Costa Rica",
    flag: "🇨🇷",
  },
  {
    iso_3166_1: "CS",
    english_name: "Serbia and Montenegro",
    native_name: "Serbia and Montenegro",
    flag: "🇷🇸",
  },
  {
    iso_3166_1: "CU",
    english_name: "Cuba",
    native_name: "Cuba",
    flag: "🇨🇺",
  },
  {
    iso_3166_1: "CV",
    english_name: "Cape Verde",
    native_name: "Cape Verde",
    flag: "🇨🇻",
  },
  {
    iso_3166_1: "CX",
    english_name: "Christmas Island",
    native_name: "Christmas Island",
    flag: "🇨🇽",
  },
  {
    iso_3166_1: "CY",
    english_name: "Cyprus",
    native_name: "Cyprus",
    flag: "🇨🇾",
  },
  {
    iso_3166_1: "CZ",
    english_name: "Czech Republic",
    native_name: "Czech Republic",
    flag: "🇨🇿",
  },
  {
    iso_3166_1: "DE",
    english_name: "Germany",
    native_name: "Germany",
    flag: "🇩🇪",
  },
  {
    iso_3166_1: "DJ",
    english_name: "Djibouti",
    native_name: "Djibouti",
    flag: "🇩🇯",
  },
  {
    iso_3166_1: "DK",
    english_name: "Denmark",
    native_name: "Denmark",
    flag: "🇩🇰",
  },
  {
    iso_3166_1: "DM",
    english_name: "Dominica",
    native_name: "Dominica",
    flag: "🇩🇲",
  },
  {
    iso_3166_1: "DO",
    english_name: "Dominican Republic",
    native_name: "Dominican Republic",
    flag: "🇩🇴",
  },
  {
    iso_3166_1: "DZ",
    english_name: "Algeria",
    native_name: "Algeria",
    flag: "🇩🇿",
  },
  {
    iso_3166_1: "EC",
    english_name: "Ecuador",
    native_name: "Ecuador",
    flag: "🇪🇨",
  },
  {
    iso_3166_1: "EE",
    english_name: "Estonia",
    native_name: "Estonia",
    flag: "🇪🇪",
  },
  {
    iso_3166_1: "EG",
    english_name: "Egypt",
    native_name: "Egypt",
    flag: "🇪🇬",
  },
  {
    iso_3166_1: "EH",
    english_name: "Western Sahara",
    native_name: "Western Sahara",
    flag: "🇪🇭",
  },
  {
    iso_3166_1: "ER",
    english_name: "Eritrea",
    native_name: "Eritrea",
    flag: "🇪🇷",
  },
  {
    iso_3166_1: "ES",
    english_name: "Spain",
    native_name: "Spain",
    flag: "🇪🇸",
  },
  {
    iso_3166_1: "ET",
    english_name: "Ethiopia",
    native_name: "Ethiopia",
    flag: "🇪🇹",
  },
  {
    iso_3166_1: "FI",
    english_name: "Finland",
    native_name: "Finland",
    flag: "🇫🇮",
  },
  {
    iso_3166_1: "FJ",
    english_name: "Fiji",
    native_name: "Fiji",
    flag: "🇫🇯",
  },
  {
    iso_3166_1: "FK",
    english_name: "Falkland Islands",
    native_name: "Falkland Islands",
    flag: "🇫🇰",
  },
  {
    iso_3166_1: "FM",
    english_name: "Micronesia",
    native_name: "Micronesia",
    flag: "🇫🇲",
  },
  {
    iso_3166_1: "FO",
    english_name: "Faeroe Islands",
    native_name: "Faroe Islands",
    flag: "🇫🇴",
  },
  {
    iso_3166_1: "FR",
    english_name: "France",
    native_name: "France",
    flag: "🇫🇷",
  },
  {
    iso_3166_1: "GA",
    english_name: "Gabon",
    native_name: "Gabon",
    flag: "🇬🇦",
  },
  {
    iso_3166_1: "GB",
    english_name: "United Kingdom",
    native_name: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    iso_3166_1: "GD",
    english_name: "Grenada",
    native_name: "Grenada",
    flag: "🇬🇩",
  },
  {
    iso_3166_1: "GE",
    english_name: "Georgia",
    native_name: "Georgia",
    flag: "🇬🇪",
  },
  {
    iso_3166_1: "GF",
    english_name: "French Guiana",
    native_name: "French Guiana",
    flag: "🇬🇫",
  },
  {
    iso_3166_1: "GH",
    english_name: "Ghana",
    native_name: "Ghana",
    flag: "🇬🇭",
  },
  {
    iso_3166_1: "GI",
    english_name: "Gibraltar",
    native_name: "Gibraltar",
    flag: "🇬🇮",
  },
  {
    iso_3166_1: "GL",
    english_name: "Greenland",
    native_name: "Greenland",
    flag: "🇬🇱",
  },
  {
    iso_3166_1: "GM",
    english_name: "Gambia",
    native_name: "Gambia",
    flag: "🇬🇲",
  },
  {
    iso_3166_1: "GN",
    english_name: "Guinea",
    native_name: "Guinea",
    flag: "🇬🇳",
  },
  {
    iso_3166_1: "GP",
    english_name: "Guadaloupe",
    native_name: "Guadeloupe",
    flag: "🇬🇵",
  },
  {
    iso_3166_1: "GQ",
    english_name: "Equatorial Guinea",
    native_name: "Equatorial Guinea",
    flag: "🇬🇶",
  },
  {
    iso_3166_1: "GR",
    english_name: "Greece",
    native_name: "Greece",
    flag: "🇬🇷",
  },
  {
    iso_3166_1: "GS",
    english_name: "South Georgia and the South Sandwich Islands",
    native_name: "South Georgia & South Sandwich Islands",
    flag: "🇬🇸",
  },
  {
    iso_3166_1: "GT",
    english_name: "Guatemala",
    native_name: "Guatemala",
    flag: "🇬🇹",
  },
  {
    iso_3166_1: "GU",
    english_name: "Guam",
    native_name: "Guam",
    flag: "🇬🇺",
  },
  {
    iso_3166_1: "GW",
    english_name: "Guinea-Bissau",
    native_name: "Guinea-Bissau",
    flag: "🇬🇼",
  },
  {
    iso_3166_1: "GY",
    english_name: "Guyana",
    native_name: "Guyana",
    flag: "🇬🇾",
  },
  {
    iso_3166_1: "HK",
    english_name: "Hong Kong",
    native_name: "Hong Kong SAR China",
    flag: "🇭🇰",
  },
  {
    iso_3166_1: "HM",
    english_name: "Heard and McDonald Islands",
    native_name: "Heard & McDonald Islands",
    flag: "🇭🇲",
  },
  {
    iso_3166_1: "HN",
    english_name: "Honduras",
    native_name: "Honduras",
    flag: "🇭🇳",
  },
  {
    iso_3166_1: "HR",
    english_name: "Croatia",
    native_name: "Croatia",
    flag: "🇭🇷",
  },
  {
    iso_3166_1: "HT",
    english_name: "Haiti",
    native_name: "Haiti",
    flag: "🇭🇹",
  },
  {
    iso_3166_1: "HU",
    english_name: "Hungary",
    native_name: "Hungary",
    flag: "🇭🇺",
  },
  {
    iso_3166_1: "ID",
    english_name: "Indonesia",
    native_name: "Indonesia",
    flag: "🇮🇩",
  },
  {
    iso_3166_1: "IE",
    english_name: "Ireland",
    native_name: "Ireland",
    flag: "🇮🇪",
  },
  {
    iso_3166_1: "IL",
    english_name: "Israel",
    native_name: "Israel",
    flag: "🇮🇱",
  },
  {
    iso_3166_1: "IN",
    english_name: "India",
    native_name: "India",
    flag: "🇮🇳",
  },
  {
    iso_3166_1: "IO",
    english_name: "British Indian Ocean Territory",
    native_name: "British Indian Ocean Territory",
    flag: "🇮🇴",
  },
  {
    iso_3166_1: "IQ",
    english_name: "Iraq",
    native_name: "Iraq",
    flag: "🇮🇶",
  },
  {
    iso_3166_1: "IR",
    english_name: "Iran",
    native_name: "Iran",
    flag: "🇮🇷",
  },
  {
    iso_3166_1: "IS",
    english_name: "Iceland",
    native_name: "Iceland",
    flag: "🇮🇸",
  },
  {
    iso_3166_1: "IT",
    english_name: "Italy",
    native_name: "Italy",
    flag: "🇮🇹",
  },
  {
    iso_3166_1: "JM",
    english_name: "Jamaica",
    native_name: "Jamaica",
    flag: "🇯🇲",
  },
  {
    iso_3166_1: "JO",
    english_name: "Jordan",
    native_name: "Jordan",
    flag: "🇯🇴",
  },
  {
    iso_3166_1: "JP",
    english_name: "Japan",
    native_name: "Japan",
    flag: "🇯🇵",
  },
  {
    iso_3166_1: "KE",
    english_name: "Kenya",
    native_name: "Kenya",
    flag: "🇰🇪",
  },
  {
    iso_3166_1: "KG",
    english_name: "Kyrgyz Republic",
    native_name: "Kyrgyzstan",
    flag: "🇰🇬",
  },
  {
    iso_3166_1: "KH",
    english_name: "Cambodia",
    native_name: "Cambodia",
    flag: "🇰🇭",
  },
  {
    iso_3166_1: "KI",
    english_name: "Kiribati",
    native_name: "Kiribati",
    flag: "🇰🇮",
  },
  {
    iso_3166_1: "KM",
    english_name: "Comoros",
    native_name: "Comoros",
    flag: "🇰🇲",
  },
  {
    iso_3166_1: "KN",
    english_name: "St. Kitts and Nevis",
    native_name: "St. Kitts & Nevis",
    flag: "🇰🇳",
  },
  {
    iso_3166_1: "KP",
    english_name: "North Korea",
    native_name: "North Korea",
    flag: "🇰🇵",
  },
  {
    iso_3166_1: "KR",
    english_name: "South Korea",
    native_name: "South Korea",
    flag: "🇰🇷",
  },
  {
    iso_3166_1: "KW",
    english_name: "Kuwait",
    native_name: "Kuwait",
    flag: "🇰🇼",
  },
  {
    iso_3166_1: "KY",
    english_name: "Cayman Islands",
    native_name: "Cayman Islands",
    flag: "🇰🇾",
  },
  {
    iso_3166_1: "KZ",
    english_name: "Kazakhstan",
    native_name: "Kazakhstan",
    flag: "🇰🇿",
  },
  {
    iso_3166_1: "LA",
    english_name: "Lao People's Democratic Republic",
    native_name: "Laos",
    flag: "🇱🇦",
  },
  {
    iso_3166_1: "LB",
    english_name: "Lebanon",
    native_name: "Lebanon",
    flag: "🇱🇧",
  },
  {
    iso_3166_1: "LC",
    english_name: "St. Lucia",
    native_name: "St. Lucia",
    flag: "🇱🇨",
  },
  {
    iso_3166_1: "LI",
    english_name: "Liechtenstein",
    native_name: "Liechtenstein",
    flag: "🇱🇮",
  },
  {
    iso_3166_1: "LK",
    english_name: "Sri Lanka",
    native_name: "Sri Lanka",
    flag: "🇱🇰",
  },
  {
    iso_3166_1: "LR",
    english_name: "Liberia",
    native_name: "Liberia",
    flag: "🇱🇷",
  },
  {
    iso_3166_1: "LS",
    english_name: "Lesotho",
    native_name: "Lesotho",
    flag: "🇱🇸",
  },
  {
    iso_3166_1: "LT",
    english_name: "Lithuania",
    native_name: "Lithuania",
    flag: "🇱🇹",
  },
  {
    iso_3166_1: "LU",
    english_name: "Luxembourg",
    native_name: "Luxembourg",
    flag: "🇱🇺",
  },
  {
    iso_3166_1: "LV",
    english_name: "Latvia",
    native_name: "Latvia",
    flag: "🇱🇻",
  },
  {
    iso_3166_1: "LY",
    english_name: "Libyan Arab Jamahiriya",
    native_name: "Libya",
    flag: "🇱🇾",
  },
  {
    iso_3166_1: "MA",
    english_name: "Morocco",
    native_name: "Morocco",
    flag: "🇲🇦",
  },
  {
    iso_3166_1: "MC",
    english_name: "Monaco",
    native_name: "Monaco",
    flag: "🇲🇨",
  },
  {
    iso_3166_1: "MD",
    english_name: "Moldova",
    native_name: "Moldova",
    flag: "🇲🇩",
  },
  {
    iso_3166_1: "ME",
    english_name: "Montenegro",
    native_name: "Montenegro",
    flag: "🇲🇪",
  },
  {
    iso_3166_1: "MG",
    english_name: "Madagascar",
    native_name: "Madagascar",
    flag: "🇲🇬",
  },
  {
    iso_3166_1: "MH",
    english_name: "Marshall Islands",
    native_name: "Marshall Islands",
    flag: "🇲🇭",
  },
  {
    iso_3166_1: "MK",
    english_name: "Macedonia",
    native_name: "Macedonia",
    flag: "🇲🇰",
  },
  {
    iso_3166_1: "ML",
    english_name: "Mali",
    native_name: "Mali",
    flag: "🇲🇱",
  },
  {
    iso_3166_1: "MM",
    english_name: "Myanmar",
    native_name: "Myanmar (Burma)",
    flag: "🇲🇲",
  },
  {
    iso_3166_1: "MN",
    english_name: "Mongolia",
    native_name: "Mongolia",
    flag: "🇲🇳",
  },
  {
    iso_3166_1: "MO",
    english_name: "Macao",
    native_name: "Macau SAR China",
    flag: "🇲🇴",
  },
  {
    iso_3166_1: "MP",
    english_name: "Northern Mariana Islands",
    native_name: "Northern Mariana Islands",
    flag: "🇲🇵",
  },
  {
    iso_3166_1: "MQ",
    english_name: "Martinique",
    native_name: "Martinique",
    flag: "🇲🇶",
  },
  {
    iso_3166_1: "MR",
    english_name: "Mauritania",
    native_name: "Mauritania",
    flag: "🇲🇷",
  },
  {
    iso_3166_1: "MS",
    english_name: "Montserrat",
    native_name: "Montserrat",
    flag: "🇲🇸",
  },
  {
    iso_3166_1: "MT",
    english_name: "Malta",
    native_name: "Malta",
    flag: "🇲🇹",
  },
  {
    iso_3166_1: "MU",
    english_name: "Mauritius",
    native_name: "Mauritius",
    flag: "🇲🇺",
  },
  {
    iso_3166_1: "MV",
    english_name: "Maldives",
    native_name: "Maldives",
    flag: "🇲🇻",
  },
  {
    iso_3166_1: "MW",
    english_name: "Malawi",
    native_name: "Malawi",
    flag: "🇲🇼",
  },
  {
    iso_3166_1: "MX",
    english_name: "Mexico",
    native_name: "Mexico",
    flag: "🇲🇽",
  },
  {
    iso_3166_1: "MY",
    english_name: "Malaysia",
    native_name: "Malaysia",
    flag: "🇲🇾",
  },
  {
    iso_3166_1: "MZ",
    english_name: "Mozambique",
    native_name: "Mozambique",
    flag: "🇲🇿",
  },
  {
    iso_3166_1: "NA",
    english_name: "Namibia",
    native_name: "Namibia",
    flag: "🇳🇦",
  },
  {
    iso_3166_1: "NC",
    english_name: "New Caledonia",
    native_name: "New Caledonia",
    flag: "🇳🇨",
  },
  {
    iso_3166_1: "NE",
    english_name: "Niger",
    native_name: "Niger",
    flag: "🇳🇪",
  },
  {
    iso_3166_1: "NF",
    english_name: "Norfolk Island",
    native_name: "Norfolk Island",
    flag: "🇳🇫",
  },
  {
    iso_3166_1: "NG",
    english_name: "Nigeria",
    native_name: "Nigeria",
    flag: "🇳🇬",
  },
  {
    iso_3166_1: "NI",
    english_name: "Nicaragua",
    native_name: "Nicaragua",
    flag: "🇳🇮",
  },
  {
    iso_3166_1: "NL",
    english_name: "Netherlands",
    native_name: "Netherlands",
    flag: "🇳🇱",
  },
  {
    iso_3166_1: "NO",
    english_name: "Norway",
    native_name: "Norway",
    flag: "🇳🇴",
  },
  {
    iso_3166_1: "NP",
    english_name: "Nepal",
    native_name: "Nepal",
    flag: "🇳🇵",
  },
  {
    iso_3166_1: "NR",
    english_name: "Nauru",
    native_name: "Nauru",
    flag: "🇳🇷",
  },
  {
    iso_3166_1: "NU",
    english_name: "Niue",
    native_name: "Niue",
    flag: "🇳🇺",
  },
  {
    iso_3166_1: "NZ",
    english_name: "New Zealand",
    native_name: "New Zealand",
    flag: "🇳🇿",
  },
  {
    iso_3166_1: "OM",
    english_name: "Oman",
    native_name: "Oman",
    flag: "🇴🇲",
  },
  {
    iso_3166_1: "PA",
    english_name: "Panama",
    native_name: "Panama",
    flag: "🇵🇦",
  },
  {
    iso_3166_1: "PE",
    english_name: "Peru",
    native_name: "Peru",
    flag: "🇵🇪",
  },
  {
    iso_3166_1: "PF",
    english_name: "French Polynesia",
    native_name: "French Polynesia",
    flag: "🇵🇫",
  },
  {
    iso_3166_1: "PG",
    english_name: "Papua New Guinea",
    native_name: "Papua New Guinea",
    flag: "🇵🇬",
  },
  {
    iso_3166_1: "PH",
    english_name: "Philippines",
    native_name: "Philippines",
    flag: "🇵🇭",
  },
  {
    iso_3166_1: "PK",
    english_name: "Pakistan",
    native_name: "Pakistan",
    flag: "🇵🇰",
  },
  {
    iso_3166_1: "PL",
    english_name: "Poland",
    native_name: "Poland",
    flag: "🇵🇱",
  },
  {
    iso_3166_1: "PM",
    english_name: "St. Pierre and Miquelon",
    native_name: "St. Pierre & Miquelon",
    flag: "🇵🇲",
  },
  {
    iso_3166_1: "PN",
    english_name: "Pitcairn Island",
    native_name: "Pitcairn Islands",
    flag: "🇵🇳",
  },
  {
    iso_3166_1: "PR",
    english_name: "Puerto Rico",
    native_name: "Puerto Rico",
    flag: "🇵🇷",
  },
  {
    iso_3166_1: "PS",
    english_name: "Palestinian Territory",
    native_name: "Palestinian Territories",
    flag: "🇵🇸",
  },
  {
    iso_3166_1: "PT",
    english_name: "Portugal",
    native_name: "Portugal",
    flag: "🇵🇹",
  },
  {
    iso_3166_1: "PW",
    english_name: "Palau",
    native_name: "Palau",
    flag: "🇵🇼",
  },
  {
    iso_3166_1: "PY",
    english_name: "Paraguay",
    native_name: "Paraguay",
    flag: "🇵🇾",
  },
  {
    iso_3166_1: "QA",
    english_name: "Qatar",
    native_name: "Qatar",
    flag: "🇶🇦",
  },
  {
    iso_3166_1: "RE",
    english_name: "Reunion",
    native_name: "Réunion",
    flag: "🇷🇪",
  },
  {
    iso_3166_1: "RO",
    english_name: "Romania",
    native_name: "Romania",
    flag: "🇷🇴",
  },
  {
    iso_3166_1: "RS",
    english_name: "Serbia",
    native_name: "Serbia",
    flag: "🇷🇸",
  },
  {
    iso_3166_1: "RU",
    english_name: "Russia",
    native_name: "Russia",
    flag: "🇷🇺",
  },
  {
    iso_3166_1: "RW",
    english_name: "Rwanda",
    native_name: "Rwanda",
    flag: "🇷🇼",
  },
  {
    iso_3166_1: "SA",
    english_name: "Saudi Arabia",
    native_name: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    iso_3166_1: "SB",
    english_name: "Solomon Islands",
    native_name: "Solomon Islands",
    flag: "🇸🇧",
  },
  {
    iso_3166_1: "SC",
    english_name: "Seychelles",
    native_name: "Seychelles",
    flag: "🇸🇨",
  },
  {
    iso_3166_1: "SD",
    english_name: "Sudan",
    native_name: "Sudan",
    flag: "🇸🇩",
  },
  {
    iso_3166_1: "SE",
    english_name: "Sweden",
    native_name: "Sweden",
    flag: "🇸🇪",
  },
  {
    iso_3166_1: "SG",
    english_name: "Singapore",
    native_name: "Singapore",
    flag: "🇸🇬",
  },
  {
    iso_3166_1: "SH",
    english_name: "St. Helena",
    native_name: "St. Helena",
    flag: "🇸🇭",
  },
  {
    iso_3166_1: "SI",
    english_name: "Slovenia",
    native_name: "Slovenia",
    flag: "🇸🇮",
  },
  {
    iso_3166_1: "SJ",
    english_name: "Svalbard & Jan Mayen Islands",
    native_name: "Svalbard & Jan Mayen",
    flag: "🇸🇯",
  },
  {
    iso_3166_1: "SK",
    english_name: "Slovakia",
    native_name: "Slovakia",
    flag: "🇸🇰",
  },
  {
    iso_3166_1: "SL",
    english_name: "Sierra Leone",
    native_name: "Sierra Leone",
    flag: "🇸🇱",
  },
  {
    iso_3166_1: "SM",
    english_name: "San Marino",
    native_name: "San Marino",
    flag: "🇸🇲",
  },
  {
    iso_3166_1: "SN",
    english_name: "Senegal",
    native_name: "Senegal",
    flag: "🇸🇳",
  },
  {
    iso_3166_1: "SO",
    english_name: "Somalia",
    native_name: "Somalia",
    flag: "🇸🇴",
  },
  {
    iso_3166_1: "SR",
    english_name: "Suriname",
    native_name: "Suriname",
    flag: "🇸🇷",
  },
  {
    iso_3166_1: "SS",
    english_name: "South Sudan",
    native_name: "South Sudan",
    flag: "🇸🇸",
  },
  {
    iso_3166_1: "ST",
    english_name: "Sao Tome and Principe",
    native_name: "São Tomé & Príncipe",
    flag: "🇸🇹",
  },
  {
    iso_3166_1: "SU",
    english_name: "Soviet Union",
    native_name: "Soviet Union",
    flag: "🚩",
  },
  {
    iso_3166_1: "SV",
    english_name: "El Salvador",
    native_name: "El Salvador",
    flag: "🇸🇻",
  },
  {
    iso_3166_1: "SY",
    english_name: "Syrian Arab Republic",
    native_name: "Syria",
    flag: "🇸🇾",
  },
  {
    iso_3166_1: "SZ",
    english_name: "Swaziland",
    native_name: "Eswatini (Swaziland)",
    flag: "🇸🇿",
  },
  {
    iso_3166_1: "TC",
    english_name: "Turks and Caicos Islands",
    native_name: "Turks & Caicos Islands",
    flag: "🇹🇨",
  },
  {
    iso_3166_1: "TD",
    english_name: "Chad",
    native_name: "Chad",
    flag: "🇹🇩",
  },
  {
    iso_3166_1: "TF",
    english_name: "French Southern Territories",
    native_name: "French Southern Territories",
    flag: "🇹🇫",
  },
  {
    iso_3166_1: "TG",
    english_name: "Togo",
    native_name: "Togo",
    flag: "🇹🇬",
  },
  {
    iso_3166_1: "TH",
    english_name: "Thailand",
    native_name: "Thailand",
    flag: "🇹🇭",
  },
  {
    iso_3166_1: "TJ",
    english_name: "Tajikistan",
    native_name: "Tajikistan",
    flag: "🇹🇯",
  },
  {
    iso_3166_1: "TK",
    english_name: "Tokelau",
    native_name: "Tokelau",
    flag: "🇹🇰",
  },
  {
    iso_3166_1: "TL",
    english_name: "Timor-Leste",
    native_name: "Timor-Leste",
    flag: "🇹🇱",
  },
  {
    iso_3166_1: "TM",
    english_name: "Turkmenistan",
    native_name: "Turkmenistan",
    flag: "🇹🇲",
  },
  {
    iso_3166_1: "TN",
    english_name: "Tunisia",
    native_name: "Tunisia",
    flag: "🇹🇳",
  },
  {
    iso_3166_1: "TO",
    english_name: "Tonga",
    native_name: "Tonga",
    flag: "🇹🇴",
  },
  {
    iso_3166_1: "TP",
    english_name: "East Timor",
    native_name: "East Timor",
    flag: "🇹🇱",
  },
  {
    iso_3166_1: "TR",
    english_name: "Turkey",
    native_name: "Turkey",
    flag: "🇹🇷",
  },
  {
    iso_3166_1: "TT",
    english_name: "Trinidad and Tobago",
    native_name: "Trinidad & Tobago",
    flag: "🇹🇹",
  },
  {
    iso_3166_1: "TV",
    english_name: "Tuvalu",
    native_name: "Tuvalu",
    flag: "🇹🇻",
  },
  {
    iso_3166_1: "TW",
    english_name: "Taiwan",
    native_name: "Taiwan",
    flag: "🇹🇼",
  },
  {
    iso_3166_1: "TZ",
    english_name: "Tanzania",
    native_name: "Tanzania",
    flag: "🇹🇿",
  },
  {
    iso_3166_1: "UA",
    english_name: "Ukraine",
    native_name: "Ukraine",
    flag: "🇺🇦",
  },
  {
    iso_3166_1: "UG",
    english_name: "Uganda",
    native_name: "Uganda",
    flag: "🇺🇬",
  },
  {
    iso_3166_1: "UM",
    english_name: "United States Minor Outlying Islands",
    native_name: "U.S. Outlying Islands",
    flag: "🇺🇲",
  },
  {
    iso_3166_1: "US",
    english_name: "United States of America",
    native_name: "United States",
    flag: "🇺🇸",
  },
  {
    iso_3166_1: "UY",
    english_name: "Uruguay",
    native_name: "Uruguay",
    flag: "🇺🇾",
  },
  {
    iso_3166_1: "UZ",
    english_name: "Uzbekistan",
    native_name: "Uzbekistan",
    flag: "🇺🇿",
  },
  {
    iso_3166_1: "VA",
    english_name: "Holy See",
    native_name: "Vatican City",
    flag: "🇻🇦",
  },
  {
    iso_3166_1: "VC",
    english_name: "St. Vincent and the Grenadines",
    native_name: "St. Vincent & Grenadines",
    flag: "🇻🇨",
  },
  {
    iso_3166_1: "VE",
    english_name: "Venezuela",
    native_name: "Venezuela",
    flag: "🇻🇪",
  },
  {
    iso_3166_1: "VG",
    english_name: "British Virgin Islands",
    native_name: "British Virgin Islands",
    flag: "🇻🇬",
  },
  {
    iso_3166_1: "VI",
    english_name: "US Virgin Islands",
    native_name: "U.S. Virgin Islands",
    flag: "🇻🇮",
  },
  {
    iso_3166_1: "VN",
    english_name: "Vietnam",
    native_name: "Vietnam",
    flag: "🇻🇳",
  },
  {
    iso_3166_1: "VU",
    english_name: "Vanuatu",
    native_name: "Vanuatu",
    flag: "🇻🇺",
  },
  {
    iso_3166_1: "WF",
    english_name: "Wallis and Futuna Islands",
    native_name: "Wallis & Futuna",
    flag: "🇼🇫",
  },
  {
    iso_3166_1: "WS",
    english_name: "Samoa",
    native_name: "Samoa",
    flag: "🇼🇸",
  },
  {
    iso_3166_1: "XC",
    english_name: "Czechoslovakia",
    native_name: "Czechoslovakia",
    flag: "🇨🇿",
  },
  {
    iso_3166_1: "XG",
    english_name: "East Germany",
    native_name: "East Germany",
    flag: "🇩🇪",
  },
  {
    iso_3166_1: "XI",
    english_name: "Northern Ireland",
    native_name: "Northern Ireland",
    flag: "🇬🇧",
  },
  {
    iso_3166_1: "XK",
    english_name: "Kosovo",
    native_name: "Kosovo",
    flag: "🇽🇰",
  },
  {
    iso_3166_1: "YE",
    english_name: "Yemen",
    native_name: "Yemen",
    flag: "🇾🇪",
  },
  {
    iso_3166_1: "YT",
    english_name: "Mayotte",
    native_name: "Mayotte",
    flag: "🇾🇹",
  },
  {
    iso_3166_1: "YU",
    english_name: "Yugoslavia",
    native_name: "Yugoslavia",
    flag: "🇷🇸",
  },
  {
    iso_3166_1: "ZA",
    english_name: "South Africa",
    native_name: "South Africa",
    flag: "🇿🇦",
  },
  {
    iso_3166_1: "ZM",
    english_name: "Zambia",
    native_name: "Zambia",
    flag: "🇿🇲",
  },
  {
    iso_3166_1: "ZR",
    english_name: "Zaire",
    native_name: "Zaire",
    flag: "🇨🇩",
  },
  {
    iso_3166_1: "ZW",
    english_name: "Zimbabwe",
    native_name: "Zimbabwe",
    flag: "🇿🇼",
  },
];
