export const heroData = [
  {
    id: 1,
    title: "John Wick Chapter 4",
    backdrop: "https://image.tmdb.org/t/p/original/i3OTGmLNOZIo4SRQLVfLjeWegB6.jpg",
    logo: "https://image.tmdb.org/t/p/original/uhgjx0wnElaHilAx1zDV9CVc65w.png",
    genre: "Action, Thriller",
    ageRating: "13+",
    year: "2023",
  },
  {
    id: 2,
    title: "Spider-Man: No Way Home",
    backdrop: "https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    logo: "https://image.tmdb.org/t/p/original/dEFxlY8tBr3MfcofIJKzqQKVe6B.png",
    genre: "Action, Adventure, Sci-Fi",
    ageRating: "13+",
    year: "2021",
  },
  {
    id: 3,
    title: "The Batman",
    backdrop: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    logo: "https://image.tmdb.org/t/p/original/duEXZeDwJoOg0AGFKpHKsrkhifc.png",
    genre: "Action, Crime, Drama",
    ageRating: "13+",
    year: "2022",
  },
  {
    id: 4,
    title: "Top Gun: Maverick",
    backdrop: "https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
    logo: "https://image.tmdb.org/t/p/original/xGumNgL4pw3bdXDlhzAG2X4eo2I.png",
    genre: "Action, Drama",
    ageRating: "13+",
    year: "2022",
  },
];